version: '3.9'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: gourmet_db
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: gourmet_db
      JWT_SECRET_KEY: supersecretkey
      ADMIN_EMAIL: admin@legourmet.com
      ADMIN_PASSWORD: Admin123!
    depends_on:
      - mongo
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '3000:80'

volumes:
  mongo-data:
